name: Free Ubuntu VPS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up tmate session
      run: |
        sudo apt-get update
        sudo apt-get install -y tmate
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait tmate-ready
        echo "SSH session is ready!"
        tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
        tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
